EMBL-EBI-SUBS/subs-api

localdevDockerfile

run
docker build -t <image-name:tag> -f localdevDockerfile .

Faster docker build

---

build.gradle
src/main/java/uk/ac/ebi/subs/api/config/SubsAAPWebSecurityConfig.java
src/main/java/uk/ac/ebi/subs/api/controllers/TeamController.java
src/main/resources/application.properties
src/test/java/uk/ac/ebi/subs/api/AAPIntegrationTest.java
src/test/java/uk/ac/ebi/subs/api/ApiDocumentation.java
src/test/java/uk/ac/ebi/subs/api/ApiIntegrationTest.java
src/test/java/uk/ac/ebi/subs/api/ApiIntegrationTestRabbitDependent.java
src/test/java/uk/ac/ebi/subs/api/BasicAuthApiIntegrationTest.java
src/test/java/uk/ac/ebi/subs/api/CoreValidatorTest.java
src/test/java/uk/ac/ebi/subs/api/Helpers.java
src/test/java/uk/ac/ebi/subs/api/SubmissionSerialisationTest.java
src/test/java/uk/ac/ebi/subs/api/SubmittableHandlerTest.java
src/test/java/uk/ac/ebi/subs/api/TestWebSecurityConfig.java
src/test/resources/application.properties

Merge of changes previously approved in SUBS-700

Subs 743 subs api merge

---

build.gradle
src/main/java/uk/ac/ebi/subs/api/controllers/ProcessingStatusController.java
src/main/java/uk/ac/ebi/subs/api/controllers/SubmissionStatusController.java
src/main/resources/docs/how_to_submit_data_programatically.adoc
src/test/java/uk/ac/ebi/subs/api/ApiDocumentation.java

Secures SubmissionContentsController and SubmissionStatusController

Subs 611 additional security

---

build.gradle
src/main/resources/docs/how_to_submit_data_programatically.adoc
src/test/java/uk/ac/ebi/subs/api/ApiDocumentation.java

Documentation fixes

---

src/main/resources/docs/how_to_submit_data_programatically.adoc
src/main/resources/docs/submission_api.adoc

Also added 'Getting more information' section

[subs-854] Improve the documentation about the sample

---

src/main/resources/docs/how_to_submit_data_programatically.adoc

Also replaced localhost to a proper url

Add a note for adding a user to a team section

---

build.gradle
src/main/java/uk/ac/ebi/subs/api/controllers/TeamController.java
src/main/java/uk/ac/ebi/subs/api/controllers/UserItemsController.java
src/main/java/uk/ac/ebi/subs/api/processors/RootEndpointLinkProcessor.java
src/main/java/uk/ac/ebi/subs/api/services/UserTeamService.java
src/main/resources/docs/submission_api.adoc
src/test/java/uk/ac/ebi/subs/api/AAPIntegrationTest.java
src/test/java/uk/ac/ebi/subs/api/ApiDocumentation.java
src/test/java/uk/ac/ebi/subs/api/ApiIntegrationTest.java
src/test/java/uk/ac/ebi/subs/api/Helpers.java

SUBS 970 dashboard queries

---

build.gradle
src/main/java/uk/ac/ebi/subs/api/config/StudyDataTypeConfig.java
src/main/java/uk/ac/ebi/subs/api/controllers/StudyDataTypeController.java
src/main/java/uk/ac/ebi/subs/api/processors/RootEndpointLinkProcessor.java
src/main/resources/docs/submission_api.adoc
src/test/java/uk/ac/ebi/subs/api/ApiDocumentation.java

endpoint to show available data types

SUBS 984 list study data types

---

build.gradle
src/main/java/uk/ac/ebi/subs/api/config/AapLinkConfig.java
src/main/java/uk/ac/ebi/subs/api/config/StudyDataTypeConfig.java
src/main/java/uk/ac/ebi/subs/api/processors/RootEndpointLinkProcessor.java
src/main/resources/application.properties
src/test/java/uk/ac/ebi/subs/api/ApiDocumentation.java

Include link to AAP API in our root endpoint

SUBS 1007 aap api link

---

build.gradle
src/main/java/uk/ac/ebi/subs/api/processors/SubmissionContentsProcessor.java
src/main/resources/docs/how_to_submit_data_programatically.adoc
src/main/resources/docs/submission_api.adoc
src/test/java/uk/ac/ebi/subs/api/Helpers.java
src/test/java/uk/ac/ebi/subs/api/documentation/ApiDocumentation.java

SUBS 1010 project links docs

---

src/main/java/uk/ac/ebi/subs/api/config/ValidatorConfig.java
src/main/java/uk/ac/ebi/subs/api/controllers/SheetsController.java
src/main/java/uk/ac/ebi/subs/api/validators/SheetDeleteValidator.java
src/main/java/uk/ac/ebi/subs/api/validators/SheetValidator.java
src/main/resources/docs/submission_api.adoc
src/test/java/uk/ac/ebi/subs/api/documentation/SpreadsheetDocumentation.java

added limited validation for sheets, just enough to allow creation and status changes.

SUBS 1036 sheet validator

---

src/main/java/uk/ac/ebi/subs/api/validators/CoreSubmittableValidationHelper.java
src/main/java/uk/ac/ebi/subs/api/validators/SubsApiErrors.java
src/test/java/uk/ac/ebi/subs/api/ApiIntegrationTest.java
src/test/java/uk/ac/ebi/subs/api/CoreValidatorTest.java
src/test/java/uk/ac/ebi/subs/api/Helpers.java
src/test/java/uk/ac/ebi/subs/api/documentation/ApiDocumentation.java

As described in https://www.ebi.ac.uk/panda/jira/browse/SUBS-1065

SUBS-1065 Submittable resubmission bug

---

.gitignore
src/main/java/uk/ac/ebi/subs/api/validators/CoreSubmittableValidationHelper.java
src/main/java/uk/ac/ebi/subs/api/validators/SubsApiErrors.java

⚠️ This is a partial fix on [SUBS-1073](https://www.ebi.ac.uk/panda/jira/browse/SUBS-1073), please don't delete feature branch.

WIP SUBS-1073 partial fix

---

build.gradle
src/docs/asciidoc/guide_getting_started.adoc
src/docs/asciidoc/ref_samples.adoc
src/docs/asciidoc/ref_teams.adoc

SUBS 1083 documention fixes

---

build.gradle
src/main/java/uk/ac/ebi/subs/api/services/SheetService.java
src/main/java/uk/ac/ebi/subs/api/validators/SheetValidator.java
src/main/java/uk/ac/ebi/subs/api/validators/SubsApiErrors.java
src/test/java/uk/ac/ebi/subs/api/SheetValidatorTest.java

update sheet validation to pre-process cells to JSON
Please merge at the same time as changes to core-processing

SUBS 1101 sheet datatype

---

src/docs/asciidoc/ref_spreadsheets_and_templates.adoc
src/main/java/uk/ac/ebi/subs/api/validators/SheetValidator.java
src/test/java/uk/ac/ebi/subs/api/documentation/SpreadsheetDocumentation.java

Validate for empty sheets and correct a docs error

SUBS 1137 sheet validation + docs

---

build.gradle
src/main/resources/application.properties

process the application properties file to include the current version and project name

process the application properties file to include the current version and project name

---

build.gradle
src/main/java/uk/ac/ebi/subs/api/controllers/SubmissionContentsController.java
src/main/java/uk/ac/ebi/subs/api/controllers/SubmissionController.java
src/main/java/uk/ac/ebi/subs/api/controllers/TemplateController.java
src/main/java/uk/ac/ebi/subs/api/controllers/UserProjectsController.java
src/main/java/uk/ac/ebi/subs/api/controllers/UserSubmissionsController.java
src/main/java/uk/ac/ebi/subs/api/services/IdentifiablePageToProjectionPage.java

standardised on rest controller annotation where possible

cleanup of the controllers package

---

build.gradle
src/main/java/uk/ac/ebi/subs/api/handlers/CoreSubmittableEventHelper.java
src/main/java/uk/ac/ebi/subs/api/services/ChainedValidationService.java
src/test/java/uk/ac/ebi/subs/api/services/ChainedValidationServiceTest.java

For review on Thursday (01/03/2018) team meeting.

Subs 1078 - Chained Validation

---

build.gradle
src/main/java/uk/ac/ebi/subs/api/config/SubsAAPWebSecurityConfig.java
src/main/java/uk/ac/ebi/subs/api/controllers/HealthStatusSummaryController.java

Fix to allow simple text based tests of app health

SUBS 1154 simplified health status

---

build.gradle
src/test/java/uk/ac/ebi/tsc/aap/client/security/WithMockAAPUserSecurityContextFactory.java

upgrade spring boot dependencies

---

build.gradle
src/main/java/uk/ac/ebi/subs/api/handlers/SheetHandler.java
src/main/java/uk/ac/ebi/subs/api/sheetloader/SheetLoaderQueueConfig.java
src/main/java/uk/ac/ebi/subs/api/sheetloader/SheetLoaderRabbitBridge.java

Reverts EMBL-EBI-SUBS/subs-api#116

Revert "test: does reducing the message size improve performance?"

---

src/test/java/uk/ac/ebi/subs/api/SheetEventHandlerTest.java

performance is bad, does this help?

experiment: does a smaller message size help?

---

build.gradle
src/main/java/uk/ac/ebi/subs/api/sheetloader/SheetLoaderService.java
src/test/java/uk/ac/ebi/subs/api/PerfTest.java
src/test/java/uk/ac/ebi/subs/api/sheetloader/SheetLoaderPerfTest.java
src/test/java/uk/ac/ebi/subs/api/sheetloader/SheetLoaderTest.java

Use a simple stop watch to note real time spent in each method, so we can understand where performance on the server differs from our laptops

SUBS 1143 intrument slow methods

---

build.gradle

https://spring.io/blog/2018/04/11/multiple-cve-reports-published-for-spr
ing-data

update spring boot in response to CVE

---

.travis.yml
build.gradle
src/main/java/uk/ac/ebi/subs/api/controllers/TeamSubmissionController.java
src/main/java/uk/ac/ebi/subs/api/validators/SubsApiErrors.java
src/main/java/uk/ac/ebi/subs/api/validators/TeamValidator.java
src/test/java/uk/ac/ebi/subs/api/ApiIntegrationTestHelper.java
src/test/java/uk/ac/ebi/subs/api/CoreValidatorTest.java
src/test/java/uk/ac/ebi/subs/api/ProjectValidationTest.java
src/test/java/uk/ac/ebi/subs/api/SubmissionAuditTest.java
src/test/java/uk/ac/ebi/subs/api/SubmissionControllerTest.java
src/test/java/uk/ac/ebi/subs/api/TestWebSecurityConfig.java
src/test/java/uk/ac/ebi/subs/api/documentation/ApiDocumentation.java
src/test/java/uk/ac/ebi/subs/api/documentation/TeamDocumentation.java
src/test/java/uk/ac/ebi/subs/api/documentation/TemplateDocumentation.java
src/test/java/uk/ac/ebi/subs/api/documentation/UiItemSupportDocumentation.java
src/test/java/uk/ac/ebi/subs/api/validators/FileDeleteValidatorTest.java
src/test/java/uk/ac/ebi/subs/api/validators/TeamValidatorTest.java
src/test/java/uk/ac/ebi/tsc/aap/client/security/WithMockAAPUserSecurityContextFactory.java

This PR improves error messages where a user tries to create a submission without having filled in enough profile information, and brings the team creation documentation inline with our requirements.

SUBS-1227 and 1228

---

build.gradle
src/main/java/uk/ac/ebi/subs/api/config/TusUploadConfig.java
src/main/java/uk/ac/ebi/subs/api/processors/RootEndpointLinkProcessor.java
src/main/resources/application.properties
src/test/java/uk/ac/ebi/subs/api/documentation/ApiDocumentation.java

allow clients to discover upload target from API root

SUBS 1235 tus root

---

build.gradle
src/main/java/uk/ac/ebi/subs/api/controllers/UserProjectsController.java

Use a new projection interface for user's projects list to return an additional field: release date + all the submittable projection

[SUBS-1630] Use new projection for user project list

---

build.gradle
src/main/resources/logback.xml

Define the application from an environmental variable

 Merge DEV to Master

---

build.gradle

Add releaseDate field to Study

[SUBS-1662] Update to the latest subs-data-model (2.9.0)

---

build.gradle
src/main/java/uk/ac/ebi/subs/api/handlers/SubmissionStatusEventHandler.java
src/main/java/uk/ac/ebi/subs/api/services/SubmissionEventService.java
src/main/java/uk/ac/ebi/subs/api/services/SubmissionEventServiceImpl.java
src/test/java/uk/ac/ebi/subs/api/documentation/DocumentationHelper.java
src/test/java/uk/ac/ebi/subs/api/documentation/SubmissionApiDocumentation.java

Get user's JWT Token from http request header, set it on the SubmissionEnvelope and send it

[SUBS-1683] Send user's JWT token with SubmissionEnvelope

---

build.gradle
src/docs/asciidoc/docinfo.html
src/main/java/uk/ac/ebi/subs/api/config/StatusConfiguration.java

Changes:
- Remove login button, because we don't want people to try and log in right now as we don't have a UI ready
- Change background picture in the title

[SUBS-1729] Refactor the API documentation page

---

build.gradle
src/docs/asciidoc/guide_accounts_and_logging_in.adoc
src/docs/asciidoc/guide_file_upload.adoc
src/docs/asciidoc/ref_file_upload.adoc
src/docs/asciidoc/ref_spreadsheets_and_templates.adoc
src/test/java/uk/ac/ebi/subs/api/documentation/DocumentationHelper.java
src/test/java/uk/ac/ebi/subs/api/documentation/TeamDocumentation.java

Changes:
- Fix the "Authorization" header appearance in our API documentation
- Fix small documentation issue in the file-upload section

Merge API documentation changes to Master

---

build.gradle
src/main/java/uk/ac/ebi/subs/api/controllers/SubmissionContentsController.java
src/main/java/uk/ac/ebi/subs/api/error/ChecklistNotFoundException.java
src/main/java/uk/ac/ebi/subs/api/error/CustomErrorResponse.java
src/main/java/uk/ac/ebi/subs/api/error/CustomRestExceptionHandler.java
src/test/java/uk/ac/ebi/subs/api/ApiIntegrationTest.java
src/test/java/uk/ac/ebi/subs/api/Helpers.java
src/test/java/uk/ac/ebi/subs/api/controllers/SubmissionContentsControllerTest.java
src/test/java/uk/ac/ebi/subs/api/controllers/SubmissionContentsControllerWithChecklistTest.java
src/test/java/uk/ac/ebi/subs/api/utils/SubmittableHelper.java

Changes:
- Add the possibility to set a checklist for a submittable for additional schema validation

[SUBS-1801] Add the possibility to set a checklist for a submittable

---

build.gradle
src/main/java/uk/ac/ebi/subs/api/sheetloader/SheetLoaderService.java
src/test/java/uk/ac/ebi/subs/api/sheetloader/SheetLoaderTest.java

Changes:
- Add the possibility to set an additional checklist to a submittable uploaded by spreadsheet by a user from the UI

[SUBS-1802] Add possibility to set a checklist to a submittable uploaded by a spreadsheet

---

build.gradle
src/main/java/uk/ac/ebi/subs/api/handlers/SubmissionStatusEventHandler.java

- submissionDate is now set before the submitted event is raised.

SUBS-1825-release-date

---

build.gradle
src/main/java/uk/ac/ebi/subs/api/controllers/ValidationSchemaController.java
src/main/java/uk/ac/ebi/subs/api/processors/RootEndpointLinkProcessor.java
src/test/java/uk/ac/ebi/subs/api/controllers/ValidationSchemaControllerTest.java
src/test/java/uk/ac/ebi/subs/api/documentation/CoreApiDocumentation.java
src/test/resources/testResources/validationSchemaFor-dataTypeId.json

Changes:
- Add endpoints for validation schemas (list and specific one)
- Add the link of the validation schema list to the root endpoint

[SUBS-1790] Add endpoints for validation schema

---

build.gradle
src/main/java/uk/ac/ebi/subs/api/config/SubsAAPWebSecurityConfig.java

Changes:
- Remove AAP authentication from validationSchemas endpoints

[SUBS-1790] Remove AAP authentication from validationSchemas endpoints

---

build.gradle
src/main/java/uk/ac/ebi/subs/api/controllers/ValidationSchemaController.java

Changes:
- Add response's content type for the validation schema list endpoint

[SUBS-1790] Add response's content type for the validation schema list endpoint

---

build.gradle
src/main/java/uk/ac/ebi/subs/api/config/SubsAAPWebSecurityConfig.java
src/main/java/uk/ac/ebi/subs/api/controllers/ValidationSchemaController.java

Changes:
- Add response's content type for the validation schema list endpoint

Merge v2.35.2-SNAPSHOT to Master

---

RELEASE.adoc
build.gradle
src/docs/asciidoc/index.adoc

Changes:
- Remove DC maintenance banner

Remove dc maintenance banner

---

build.gradle
src/docs/asciidoc/ref_samples.adoc
src/docs/asciidoc/ref_spreadsheets_and_templates.adoc
src/docs/asciidoc/ref_validation_schemas.adoc
src/docs/asciidoc/reference-list.adoc
src/test/java/uk/ac/ebi/subs/api/controllers/SubmissionContentsControllerWithChecklistTest.java
src/test/java/uk/ac/ebi/subs/api/controllers/ValidationSchemaControllerTest.java
src/test/java/uk/ac/ebi/subs/api/documentation/SubmissionApiDocumentation.java
src/test/java/uk/ac/ebi/subs/api/documentation/ValidationSchemaDocumentation.java
src/test/java/uk/ac/ebi/subs/api/utils/ValidationSchemaHelper.java

Changes:
- Add API documentation for sample external references and validation schemas

[SUBS-1906] Document sample external refs and validation schemas

---

build.gradle
src/test/java/uk/ac/ebi/subs/api/controllers/SubmissionContentsControllerWithChecklistTest.java

Changes:
- Add missing field to SubmittableWithStatus projection
- Add missing assertions to sample external reference test

[SUBS-1915] Fix submittable with Status projection

---

build.gradle
src/docs/asciidoc/ref_samples.adoc
src/docs/asciidoc/ref_validation_schemas.adoc

Changes:
- Improve API documentation for sample and validation schema

[SUBS-1906] Improve API documentation for sample and validation schema

---

build.gradle
src/test/java/uk/ac/ebi/subs/api/documentation/SubmissionPlanDocumentation.java

Changes:
- Add enabled field to SubmissionPlan

[SUBS-1919] Add enabled field to SubmissionPlan

---

build.gradle
src/main/java/uk/ac/ebi/subs/api/sheetloader/SheetBulkOps.java

Changes:
- Set processing status on a newly created submittable from a spreadsheet

[SUBS-1922] Set processing status on a newly created submittable from a spreadsheet

---

build.gradle
src/main/java/uk/ac/ebi/subs/api/processors/SubmissionContentsProcessor.java

Changes:
- Add `files` data type to the list of data types of a submission content

[SUBS-1931] Add files data type to the list of data types of a submission content
